version: '3.8'

services:
    db:
        image: "postgres:11"
        restart: always
        volumes:
            -  postgresql_data:/var/lib/postgresql/data
        hostname: postgres
        environment:
            POSTGRES_DB: employees
            POSTGRES_USER: usr
            POSTGRES_PASSWORD: passwd
        ports:
            - "5433:5432"

volumes:
    postgresql_data:
